name: Verify Automation Health

on:
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - main

env:
  GENERATED_AUTHOR: BennyKitchell
  BASE_BRANCH: main

jobs:
  node_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: npm ci

      - name: Check commit authors
        run: |
          chmod +x ./scripts/verifiy_automation_health.sh
          ./scripts/verifiy_automation_health.sh $GENERATED_AUTHOR $BASE_BRANCH
